# Generated by Django 3.1.7 on 2021-04-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
